Updatety hive-replace

diff --git a/hive-replace b/hive-replace
--- a/hive-replace
+++ b/hive-replace
@@ -10,14 +10,10 @@ root_dev=""
 farm_hash=""
 farm=""
 thishive=0
-
 [[ $(uname -sr) == *hive* ]] && thishive=1
 
 # Prevent start from local console
-if [[ $(tty) == *tty* || ! -z $DISPLAY ]]; then
-    echo "This script doesn't work in the local console. Exiting."
-    exit
-fi
+[[ $(tty) == *tty* || ! -z $DISPLAY ]] && echo "This script doesn't work in the local console. Exiting." && exit
 
 # Get root
 if [[ $(id -u) -ne 0 ]]; then
@@ -28,18 +24,18 @@ fi
 
 function get {
     cd "$TMPDIR"
-    rm "$TMPDIR/*hive*zip" > /dev/null 2>&1
+    rm "$TMPDIR"/*hive*img.xz > /dev/null 2>&1
 
     if [[ ! -z $url ]]; then
         echo -e "${GREEN}\nCurrent URL|path to HiveOS image is ${YELLOW}\"$url\"${GREEN}.\nIf this URL|path is correct, press ENTER, or re-type the correct URL|path.${NOCOLOR}"
     fi
-    echo -en "${GREEN}\nLink|path to zip-file with HiveOS image (HTTP|FTP link or local|NFS path): ${NOCOLOR}"
+    echo -en "${GREEN}\nLink|path to HiveOS image (HTTP|FTP link or local path): ${NOCOLOR}"
     read -r answer
     [[ ! -z $answer ]] && url=$answer
 
     # Copy|download hive image to tmpfs
     echo -e "${GREEN}\nGet HiveOS image${NOCOLOR}"
-    if [[ "$url" == *http* ||  "$url" == *ftp* ]]; then
+    if [[ "$url" == *http* || "$url" == *ftp* ]]; then
         echo ""
         wget -t 5 --show-progress "$url"
         [[ $? -ne 0 ]] && echo "${RED}Download Hive OS image failed. Check URL${NOCOLOR}" && return 1
@@ -49,16 +45,23 @@ function get {
         [[ $? -ne 0 ]] && echo "${RED}Copy Hive OS image failed${NOCOLOR}" && return 1
     fi
 
+    # Verify file extension and handle img.xz format
+    if [[ "$url" == *.img.xz ]]; then
+        arch="$TMPDIR/$(basename "$url")"
+        mv "$arch" "$TMPDIR/hiveos.img.xz"
+        unxz "$TMPDIR/hiveos.img.xz"
+    fi
+
     # Get correct md5sum from Hive repo
     curl -s "$md5_url" > "$TMPDIR/VERSIONS.txt"
     [[ $? -ne 0 ]] && echo "${RED}Can't get the required data from Hive OS server. Check your internet connection${NOCOLOR}" && return 1
     archname=$(basename "$url")
     mdsum=$(sed -n "/$archname/p" "$TMPDIR/VERSIONS.txt" | awk '{print$2}')
 
-    # Check md5
+    # Check md5sum
     echo "${GREEN}Check MD5 sum of image file${NOCOLOR}"
-    mdsum_hive=$(md5sum "$TMPDIR/$archname" | awk '{print$1}')
-    [[ $mdsum != $mdsum_hive ]] && echo "${RED}MD5 sum of image file incorrect${NOCOLOR}" && return 1
+    mdsum_hive=$(md5sum "$TMPDIR/hiveos.img" | awk '{print$1}')
+    [[ $mdsum != $mdsum_hive ]] && echo "${RED}MD5 sum of image file is incorrect${NOCOLOR}" && return 1
     echo "${GREEN}Download|copy HiveOS image success!${NOCOLOR}"
     return 0
 }
@@ -81,13 +84,13 @@ function prepare {
     echo 
     echo "Total RAM=$mem Mb"
     echo
-    [[ $mem -lt 3900 ]] && echo "${YELLOW}4 GB of memory required. Exit${NOCOLOR}" && exit
+    [[ $mem -lt 3900 ]] && echo "${YELLOW}4 GB of memory required. Exiting.${NOCOLOR}" && exit
 
     PART_UUID=$(cat /proc/cmdline | tr " " "\n" | grep "UUID" | sed 's/\(^root=UUID=\)//')
     DISK_PART=$(blkid | grep -m1 "$PART_UUID" | awk '{ print $1 }' | sed 's/://' | sed 's/\(^\/dev\/\)//')
     DISK_NAME=$(echo "${DISK_PART}" | sed 's/\([[:digit:]]\)//')
-    DISK_SIZE=$(cat /proc/partitions | grep -w "$DISK_NAME" | awk '{ printf("%.f",$3/1024)}')
-    PART_SIZE=$(cat /proc/partitions | grep -w "$DISK_PART" | awk '{ printf("%.f",$3/1024)}')
+    DISK_SIZE=$(cat /proc/partitions | grep -w "${DISK_NAME}" | awk '{ printf("%.f",$3/1024)}')
+    PART_SIZE=$(cat /proc/partitions | grep -w "${DISK_PART}" | awk '{ printf("%.f",$3/1024)}')
 
     echo -e "Current OS booted from ${GREEN}$DISK_NAME${NOCOLOR} and the whole drive size is ${WHITE}$DISK_SIZE${NOCOLOR} MB"
     [[ $DISK_SIZE -lt 8192 ]] && echo -e "\n${YELLOW}The minimum disk size for HiveOS is 8 GB${NOCOLOR}" && exit
@@ -122,7 +125,7 @@ function prepare {
     else
         farm=""
         while [[ -z $farm ]]; do
-            echo -en "${GREEN}\nType your FARM_HASH from Web-interface : ${NOCOLOR}"
+            echo -en "${GREEN}\nType your FARM_HASH from Web-interface: ${NOCOLOR}"
             read -r farm
             [[ -z $farm ]] && echo "${RED}FARM_HASH can't be empty. Please retype.${NOCOLOR}"
         done
@@ -153,31 +156,29 @@ function prepare {
 
     [[ $thishive -eq 1 ]] && miner stop > /dev/null 2>&1 && killall xinit
 
-    for SOCKET in $(systemctl list-units -t socket | awk '{print $1}' | grep -v -e ssh | grep -v -e ssh | grep -v -e network | grep -v -e ifup | grep -v -e user-sessions); do
-        systemctl stop "$SOCKET" > /dev/null 2>&1
-    done
-    for SERVICE in $(systemctl list-units -t service | awk '{print $1}' | grep -v -e ssh | grep -v -e ssh | grep -v -e network | grep -v -e ifup | grep -v -e user-sessions); do
-        systemctl stop "$SERVICE" > /dev/null 2>&1
-    done
+    for SOCKET in \
+    $(systemctl list-units -t socket | awk '{print $1}' | grep -v -e ssh | grep -v -e ssh | grep -v -e network | grep -v -e ifup | grep -v -e user-sessions); \
+    do systemctl stop $SOCKET > /dev/null 2>&1; done
+    for SERVICE in \
+    $(systemctl list-units -t service | awk '{print $1}' | grep -v -e ssh | grep -v -e ssh | grep -v -e network | grep -v -e ifup | grep -v -e user-sessions); \
+    do systemctl stop $SERVICE > /dev/null 2>&1; done
 
     pid="1"
     while [[ ! -z $pid ]]; do
-        pid=$(lsof / | grep -v ' \(mem\|txt\|rtd\|cwd\) ' | grep -v -e "$SCRIPT_NAME" | sed '2!d' | awk '{print $2}')
+        pid=$(lsof / | grep -v ' \(mem\|txt\|rtd\|cwd\) ' | grep -v -e $SCRIPT_NAME | sed '2!d' | awk '{print $2}')
         [[ -z $pid ]] && continue
-        process=$(lsof / | grep -v ' \(mem\|txt\|rtd\|cwd\) ' | grep -v -e "$SCRIPT_NAME" | sed '2!d' | awk '{print $1}')
+        process=$(lsof / | grep -v ' \(mem\|txt\|rtd\|cwd\) ' | grep -v -e $SCRIPT_NAME | sed '2!d' | awk '{print $1}')
         echo -e "Kill $process"
-        kill "$pid"
+        kill $pid
         sleep 1
     done
 
-    for MOUNTS in $(cat /proc/mounts | grep "$DISK_NAME" | awk '{print $2}'); do
-        mount -n -o remount,ro "$MOUNTS" > /dev/null 2>&1
-    done
+    for MOUNTS in $(cat /proc/mounts | grep $DISK_NAME | awk '{print $2}'); do mount -n -o remount,ro $MOUNTS > /dev/null 2>&1; done
 
-    # Get config partition and mount it to loop
-    arch=$(ls "$TMPDIR/*hive*img.xz")
+    ## Get config partition and mount it to loop
+    arch="$TMPDIR/hiveos-0.6-222-stable@230512.img.xz"
     xzcat "$arch" | dd of="$TMPDIR/conf.img" bs=1M count=50 iflag=fullblock > /dev/null 2>&1
-    begin_conf=$(( $(fdisk -l "$TMPDIR/conf.img" | grep NTFS | awk '{print $2}') * 512 ))
+    begin_conf=$(fdisk -l "$TMPDIR/conf.img" | grep NTFS | awk '{print $2}')
     conf_loop=$(losetup -f)
     losetup -o "$begin_conf" "$conf_loop" "$TMPDIR/conf.img"
     mkdir "$TMPDIR/hive-config"
@@ -224,7 +225,7 @@ function prepare {
 function write {
     cd /
 
-    arch=$(ls *hive*img.xz)
+    arch="$TMPDIR/hiveos-0.6-222-stable@230512.img.xz"
     conf_part="$root_dev"1
 
     echo -e "\n\nCreate a HIVE OS File system on $root_dev"
@@ -232,7 +233,11 @@ function write {
     echo -e "To prevent damage to your disk device,\ndo not turn off your computer until the end of the process.\n"
 
     xzcat "$arch" | dd of="/dev/$root_dev" status=progress bs=20M
-    [[ $? -ne 0 ]] && echo "Write image failed. Exit" && return
+    if [[ $? -ne 0 ]]; then
+        echo "Write image failed. Exit"
+        return
+    fi
+}
 
     # Rewrite config partition
     partprobe > /dev/null 2>&1
