Update66 hive-replace

diff --git a/hive-replace b/hive-replace
--- a/hive-replace
+++ b/hive-replace
@@ -9,10 +9,16 @@ root_dev=""
 farm_hash=""
 farm=""
 thishive=0
+
+GREEN=$(tput setaf 2)
+YELLOW=$(tput setaf 3)
+RED=$(tput setaf 1)
+NOCOLOR=$(tput sgr0)
+
 [[ $(uname -sr) == *hive* ]] && thishive=1
 
-# Prevent start from the local console
-[[ $(tty) == *tty* || ! -z $DISPLAY ]] && echo "This script doesn't work in the local console. Exit" && exit
+# Prevent starting from the local console
+[[ $(tty) == *tty* || ! -z $DISPLAY ]] && { echo "This script doesn't work in the local console. Exiting."; exit 1; }
 
 # Get root
 if [[ $(id -u) -ne 0 ]]; then
@@ -25,7 +31,10 @@ function download_hive_image {
   # Download the HiveOS image file and place it in the chosen directory
   echo -e "${GREEN}\nDownloading HiveOS image${NOCOLOR}"
   wget -q --show-progress https://download.hiveos.farm/history/hiveos-0.6-222-stable@230512.img.xz -O $INSTALL_DIR/hiveos-0.6-222-stable@230512.img.xz
-  [[ $? -ne 0 ]] && echo "${RED}Download Hive OS image failed. Check the URL${NOCOLOR}" && exit 1
+  if [[ $? -ne 0 ]]; then
+    echo "${RED}Download Hive OS image failed. Check the URL${NOCOLOR}"
+    exit 1
+  fi
 }
 
 # Call the download function to fetch the HiveOS image
@@ -41,10 +50,7 @@ function get {
     echo -en "${GREEN}\nLink|path to XZ-compressed HiveOS image (HTTP|FTP link or local|NFS path): ${NOCOLOR}"
     read answer
     [[ ! -z $answer ]] && url=$answer
-    # Add your logic for downloading or copying the HiveOS image to $INSTALL_DIR here
-  done
-}
-
+    
     # Copy|download HiveOS image to the chosen directory
     echo -e "${GREEN}\nGet HiveOS image${NOCOLOR}"
     if [[ "$url" == *http* || "$url" == *ftp* ]]; then
@@ -62,24 +68,14 @@ function get {
 }
 
 function prepare {
-  BLACK=$(tput setaf 0)
-  RED=$(tput setaf 1)
-  GREEN=$(tput setaf 2)
-  YELLOW=$(tput setaf 3)
-  BLUE=$(tput setaf 4)
-  MAGENTA=$(tput setaf 5)
-  CYAN=$(tput setaf 6)
-  WHITE=$(tput setaf 7)
-  NOCOLOR=$(tput sgr0)
-
-  mem=$(free -m | awk 'NR == 2{print$2}')
+  mem=$(free -m | awk 'NR == 2{print $2}')
   clear
   echo "***********************************"
   echo "${GREEN}Install HiveOS${NOCOLOR}"
-  echo
+  echo 
   echo "Total RAM=$mem Mb"
   echo
-  [[ $mem -lt 3900 ]] && echo "${YELLOW}4 Gb of memory required. Exit${NOCOLOR}" && exit
+  [[ $mem -lt 3900 ]] && { echo "${YELLOW}4 Gb of memory required. Exit${NOCOLOR}"; exit 1; }
 
   PART_UUID=$(cat /proc/cmdline | tr " " "\n" | grep "UUID" | sed 's/\(^root=UUID=\)//')
   DISK_PART=$(blkid | grep -m1 $PART_UUID | awk '{ print $1 }' | sed 's/://' | sed 's/\(^\/dev\/\)//')
@@ -87,23 +83,16 @@ function prepare {
   DISK_SIZE=$(cat /proc/partitions | grep -w "${DISK_NAME}" | awk '{ printf("%.f",$3/1024)}')
   PART_SIZE=$(cat /proc/partitions | grep -w "${DISK_PART}" | awk '{ printf("%.f",$3/1024)}')
 
-  echo -e "Current OS booted from ${GREEN}$DISK_NAME${NOCOLOR} and the whole drive size is ${WHITE}$DISK_SIZE${NOCOLOR} MB"
-  [[ $DISK_SIZE -lt 8192 ]] && echo -e "\n${YELLOW}The minimum disk size for HiveOS is 8 Gb${NOCOLOR}" && exit
+  echo -e "Current OS booted from ${GREEN}$DISK_NAME${NOCOLOR} and the whole drive size is ${YELLOW}$DISK_SIZE${NOCOLOR} MB"
+  [[ $DISK_SIZE -lt 8192 ]] && { echo -e "\n${YELLOW}The minimum disk size for HiveOS is 8 Gb${NOCOLOR}"; exit 1; }
   echo -e "${RED}Warning: After installing HiveOS, all your data on ${GREEN}$DISK_NAME${NOCOLOR}${RED} will be lost!${NOCOLOR}"
-  # echo -en "\nType ${GREEN}\"yes\"${NOCOLOR} if you want to install Hive OS on ${GREEN}$DISK_NAME${NOCOLOR} : "
-  # read answer
-  # [[ $answer != "yes" ]] && echo -e "${YELLOW}\nBye, bye!${NOCOLOR}" && exit
 
   # Check for necessary programs
   programs=0
-  dpkg -s lsof > /dev/null 2>&1
-  [[ $? -ne 0 ]] && programs=1
-  dpkg -s curl > /dev/null 2>&1
-  [[ $? -ne 0 ]] && programs=1
-  dpkg -s wget > /dev/null 2>&1
-  [[ $? -ne 0 ]] && programs=1
-  dpkg -s unzip > /dev/null 2>&1
-  [[ $? -ne 0 ]] && programs=1
+  dpkg -s lsof > /dev/null 2>&1 || programs=1
+  dpkg -s curl > /dev/null 2>&1 || programs=1
+  dpkg -s wget > /dev/null 2>&1 || programs=1
+  dpkg -s unzip > /dev/null 2>&1 || programs=1
   if [[ $programs -ne 0 ]]; then
     echo "Install the necessary programs"
     apt-get update
@@ -122,7 +111,7 @@ function prepare {
     while [[ -z $farm ]]; do
       echo -en "${GREEN}\nType your FARM_HASH from Web-interface : ${NOCOLOR}"
       read farm
-      [[ -z $farm ]] && echo "${RED}FARM_HASH can't be empty. Please retype.${NOCOLOR}"
+      [[ -z $farm ]] && { echo "${RED}FARM_HASH can't be empty. Please retype.${NOCOLOR}"; exit 1; }
     done
   fi
 }
@@ -137,7 +126,7 @@ while [[ $flag_get -ne 0 ]]; do
     echo -en "You want to try again (Y/n) : "
     read answer
     [[ ! -z $answer ]] && repeat=$answer
-    [[ $repeat != y* && $repeat != Y* ]] && echo -e "${YELLOW}\nBye, bye!${NOCOLOR}" && exit
+    [[ $repeat != y* && $repeat != Y* ]] && { echo -e "${YELLOW}\nBye, bye!${NOCOLOR}"; exit; }
   fi
 done
 
@@ -213,12 +202,8 @@ mount --bind /sys $INSTALL_DIR/sys
 mount --bind /dev $INSTALL_DIR/dev
 
 # Chroot to temp root
-mount --bind /proc $INSTALL_DIR/proc
-mount --bind /sys $INSTALL_DIR/sys
-mount --bind /dev $INSTALL_DIR/dev
 sync
-cd $INSTALL_DIR
-exec chroot . /bin/bash /$SCRIPT_NAME
+chroot $INSTALL_DIR /bin/bash /$SCRIPT_NAME
 }
 
 function write {
@@ -232,7 +217,7 @@ function write {
   echo -e "To prevent damage to your disk device,\ndo not turn off your computer until the end of the process.\n"
 
   xzcat $arch | dd of=/dev/$root_dev status=progress bs=20M
-  [[ $? -ne 0 ]] && echo "Write image failed. Exit" && return
+  [[ $? -ne 0 ]] && { echo "Write image failed. Exiting."; exit 1; }
 
   # Rewrite config partition
   partprobe > /dev/null 2>&1
