Updates hive-replace

diff --git a/hive-replace b/hive-replace
--- a/hive-replace
+++ b/hive-replace
@@ -32,13 +32,18 @@ function download_hive_image {
 download_hive_image
 
 function get {
-  # Remove the previous HiveOS image download check
-  # ...
+  cd $INSTALL_DIR
+  rm $INSTALL_DIR/*hive* > /dev/null 2>&1
+
+  [[ ! -z $url ]] && echo -e "${GREEN}\nCurrent URL|path to HiveOS image is ${YELLOW}\"$url\"${GREEN}.\nIf this URL|path is correct, press ENTER, or re-type the correct URL|path.${NOCOLOR}"
 
   while true; do
     echo -en "${GREEN}\nLink|path to XZ-compressed HiveOS image (HTTP|FTP link or local|NFS path): ${NOCOLOR}"
     read answer
     [[ ! -z $answer ]] && url=$answer
+    # Add your logic for downloading or copying the HiveOS image to $INSTALL_DIR here
+  done
+}
 
     # Copy|download HiveOS image to the chosen directory
     echo -e "${GREEN}\nGet HiveOS image${NOCOLOR}"
@@ -56,8 +61,71 @@ function get {
   done
 }
 
-# Rest of the script refers to $TMPDIR
-# Update these references to use $INSTALL_DIR
+function prepare {
+  BLACK=$(tput setaf 0)
+  RED=$(tput setaf 1)
+  GREEN=$(tput setaf 2)
+  YELLOW=$(tput setaf 3)
+  BLUE=$(tput setaf 4)
+  MAGENTA=$(tput setaf 5)
+  CYAN=$(tput setaf 6)
+  WHITE=$(tput setaf 7)
+  NOCOLOR=$(tput sgr0)
+
+  mem=$(free -m | awk 'NR == 2{print$2}')
+  clear
+  echo "***********************************"
+  echo "${GREEN}Install HiveOS${NOCOLOR}"
+  echo
+  echo "Total RAM=$mem Mb"
+  echo
+  [[ $mem -lt 3900 ]] && echo "${YELLOW}4 Gb of memory required. Exit${NOCOLOR}" && exit
+
+  PART_UUID=$(cat /proc/cmdline | tr " " "\n" | grep "UUID" | sed 's/\(^root=UUID=\)//')
+  DISK_PART=$(blkid | grep -m1 $PART_UUID | awk '{ print $1 }' | sed 's/://' | sed 's/\(^\/dev\/\)//')
+  DISK_NAME=$(echo ${DISK_PART} | sed 's/\([[:digit:]]\)//')
+  DISK_SIZE=$(cat /proc/partitions | grep -w "${DISK_NAME}" | awk '{ printf("%.f",$3/1024)}')
+  PART_SIZE=$(cat /proc/partitions | grep -w "${DISK_PART}" | awk '{ printf("%.f",$3/1024)}')
+
+  echo -e "Current OS booted from ${GREEN}$DISK_NAME${NOCOLOR} and the whole drive size is ${WHITE}$DISK_SIZE${NOCOLOR} MB"
+  [[ $DISK_SIZE -lt 8192 ]] && echo -e "\n${YELLOW}The minimum disk size for HiveOS is 8 Gb${NOCOLOR}" && exit
+  echo -e "${RED}Warning: After installing HiveOS, all your data on ${GREEN}$DISK_NAME${NOCOLOR}${RED} will be lost!${NOCOLOR}"
+  # echo -en "\nType ${GREEN}\"yes\"${NOCOLOR} if you want to install Hive OS on ${GREEN}$DISK_NAME${NOCOLOR} : "
+  # read answer
+  # [[ $answer != "yes" ]] && echo -e "${YELLOW}\nBye, bye!${NOCOLOR}" && exit
+
+  # Check for necessary programs
+  programs=0
+  dpkg -s lsof > /dev/null 2>&1
+  [[ $? -ne 0 ]] && programs=1
+  dpkg -s curl > /dev/null 2>&1
+  [[ $? -ne 0 ]] && programs=1
+  dpkg -s wget > /dev/null 2>&1
+  [[ $? -ne 0 ]] && programs=1
+  dpkg -s unzip > /dev/null 2>&1
+  [[ $? -ne 0 ]] && programs=1
+  if [[ $programs -ne 0 ]]; then
+    echo "Install the necessary programs"
+    apt-get update
+    apt-get install -y lsof curl wget unzip
+  fi
+
+  # Create tmpfs
+  mkdir $INSTALL_DIR > /dev/null 2>&1
+  mount none $INSTALL_DIR -t tmpfs -o size=3000m
+
+  # Get farm_hash or old config
+  if [[ $thishive -eq 1 && -f $INSTALL_DIR/hive-config/rig.conf ]]; then
+    cp $INSTALL_DIR/hive-config/rig.conf $INSTALL_DIR/
+  else
+    farm=""
+    while [[ -z $farm ]]; do
+      echo -en "${GREEN}\nType your FARM_HASH from Web-interface : ${NOCOLOR}"
+      read farm
+      [[ -z $farm ]] && echo "${RED}FARM_HASH can't be empty. Please retype.${NOCOLOR}"
+    done
+  fi
+}
 
 # Get HiveOS image
 flag_get=1
@@ -125,8 +193,24 @@ fi
 # Write image of configs partition
 dd if=$conf_loop of=$INSTALL_DIR/new_conf.img > /dev/null 2>&1
 
-# Rest of the script continues from where it left off
-# ...
+# Create temp root
+echo -e "${YELLOW}\nCreate a temporary root fs${NOCOLOR}"
+mkdir -p $INSTALL_DIR/{proc,sys,run,dev,usr,var,oldroot,bin,sbin,lib,tmp,usr/lib,usr/share,usr/lib/x86_64-linux-gnu,lib/lsb}
+cp -aR /{bin,sbin,etc} $INSTALL_DIR > /dev/null 2>&1
+cp -aR /usr/{bin,sbin} $INSTALL_DIR/usr > /dev/null 2>&1
+cp -aR /lib/x86_64-linux-gnu $INSTALL_DIR/lib > /dev/null 2>&1
+cp -aR /lib64 $INSTALL_DIR > /dev/null 2>&1
+cp -aR /usr/lib/sudo $INSTALL_DIR/usr/lib > /dev/null 2>&1
+cp -a /usr/lib/x86_64-linux-gnu/libmpfr* $INSTALL_DIR/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
+cp -a /usr/lib/x86_64-linux-gnu/libsigsegv* $INSTALL_DIR/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
+cp -a /usr/lib/x86_64-linux-gnu/libgmp* $INSTALL_DIR/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
+cp -aR /dev $INSTALL_DIR > /dev/null 2>&1
+cp $0 $INSTALL_DIR > /dev/null 2>&1
+chmod +x $INSTALL_DIR/$SCRIPT_NAME > /dev/null 2>&1
+
+mount --bind /proc $INSTALL_DIR/proc
+mount --bind /sys $INSTALL_DIR/sys
+mount --bind /dev $INSTALL_DIR/dev
 
 # Chroot to temp root
 mount --bind /proc $INSTALL_DIR/proc
@@ -148,7 +232,7 @@ function write {
   echo -e "To prevent damage to your disk device,\ndo not turn off your computer until the end of the process.\n"
 
   xzcat $arch | dd of=/dev/$root_dev status=progress bs=20M
-  [[ $? -ne 0 ]] && "Write image failed. Exit" && return
+  [[ $? -ne 0 ]] && echo "Write image failed. Exit" && return
 
   # Rewrite config partition
   partprobe > /dev/null 2>&1
