Update5 hive-replace

diff --git a/hive-replace b/hive-replace
--- a/hive-replace
+++ b/hive-replace
@@ -34,23 +34,28 @@ download_hive_image
 function get {
   cd $TMPDIR
   rm $TMPDIR/*hive* > /dev/null 2>&1
-  
+
   [[ ! -z $url ]] && echo -e "${GREEN}\nCurrent URL|path to HiveOS image is ${YELLOW}\"$url\"${GREEN}.\nIf this URL|path is correct press ENTER, or re-type correct URL|path.${NOCOLOR}"
-  echo -en "${GREEN}\nLink|path to XZ-compressed HiveOS image (HTTP|FTP link or local|NFS path): ${NOCOLOR}"
-  read answer
-  [[ ! -z $answer ]] && url=$answer
   
-  # Copy|download HiveOS image to tmpfs
-  echo -e "${GREEN}\nGet HiveOS image${NOCOLOR}"
-  if [[ "$url" == *http* ||  "$url" == *ftp* ]]; then
-    echo ""
-    wget -t 5 --show-progress $url -O $archname
-    [[ $? -ne 0 ]] && echo "${RED}Download Hive OS image failed. Check URL${NOCOLOR}" && return 1
-  else
-    [[ ! -f $url ]] && echo "${RED}Hive OS image not found. Check path${NOCOLOR}" && return 1
-    cp -v $url $TMPDIR
-    [[ $? -ne 0 ]] && echo "${RED}Copy Hive OS image failed${NOCOLOR}" && return 1
-  fi
+  while true; do
+    echo -en "${GREEN}\nLink|path to XZ-compressed HiveOS image (HTTP|FTP link or local|NFS path): ${NOCOLOR}"
+    read answer
+    [[ ! -z $answer ]] && url=$answer
+
+    # Copy|download HiveOS image to tmpfs
+    echo -e "${GREEN}\nGet HiveOS image${NOCOLOR}"
+    if [[ "$url" == *http* || "$url" == *ftp* ]]; then
+      echo ""
+      wget -t 5 --show-progress $url -O $archname
+      if [[ $? -ne 0 ]]; then
+        echo "${RED}Download Hive OS image failed. Check URL${NOCOLOR}"
+      else
+        break  # Break out of the loop on successful download
+      fi
+    else
+      [[ ! -f $url ]] && echo "${RED}Hive OS image not found. Check path${NOCOLOR}" || break  # Break out of the loop if the file exists
+    fi
+  done
 }
 
 function prepare {
